spring:
  application:
    name: itoken-config
  zipkin:
    base-url: http://47.111.117.131:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/liu-itoken/itoken-config.git
          search-paths: respo
          username: 2395546591@qq.com
          password: liu18727325467
  boot:
    admin:
      client:
        url: http://47.111.117.131:8084

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.111.117.131:8761/eureka/
