spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://47.111.117.131:9411


server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/