spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://47.111.117.131:9411
  boot:
    admin:
      client:
        url: http://47.111.117.131:8084


server:
  port: 8761

eureka:
  instance:
    hostname: 47.111.117.131
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
