spring:
  application:
    name: itonken-zipkin
  zipkin:
    base-url: http://47.111.117.131:9411
  boot:
    admin:
      client:
        url: http://47.111.117.131:8084

server:
  port: 9411


eureka:
  client:
    serviceUrl:
      defaultZone: http://47.111.117.131:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: health,info